index:
    path: /
    controller: Library\Controller\MainController::index
    methods: [GET]

add_book:
    path: /add
    controller: Library\Controller\AddBookController::add
    methods: [POST]

update_book:
    path: /{identity}/update
    controller: Library\Controller\UpdateBookController::update
    methods: [POST]

delete_book:
    path: /{identity}/delete
    controller: Library\Controller\UpdateBookController::delete
    methods: [POST]

book_form:
    path: /form
    controller: Library\Controller\FormController::index
    methods: [GET]
