index:
    path: /
    controller: Library\Controller\MController::index
    methods: [GET]

add_book:
    path: /add_book
    controller: Library\Controller\AddBookController::index
    methods: [POST]

add_form:
    path: /form
    controller: Library\Controller\FormController::index
    methods: [GET]
